image: registry.gitlab.com/yawik/docker/build

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "$CI_PROJECT_DIR/vendor/"
    - "$CI_PROJECT_DIR/node_modules//"
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

stages:
  - build
  - test

services:
  - mongo:latest

before_script:
  - ls -la

composer:
  stage: build
  cache:
    key: build-cache
    paths:
    - vendor/
  script:
    - pwd
    - su yawik -c "composer install"

phpunit:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - ./vendor/bin/phpunit

behat:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - su yawik -c "composer install"
    - mkdir -p build/behat
    - mkdir -p build/mails
    - ./bin/start-selenium > /dev/null 2>&1 &
    - sleep 5
    - composer run serve --timeout=0 > /dev/null 2>&1 &
    - ./vendor/bin/behat --strict --no-interaction