image: registry.gitlab.com/yawik/docker/build

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "$CI_PROJECT_DIR/vendor/"
    - "$CI_PROJECT_DIR/node_modules//"
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

stages:
  - build
  - test
  - deploy

services:
  - mongo:latest
  - selenium/standalone-chrome
  
before_script:
  - ls -la

composer:
  stage: build
  cache:
    key: build-cache
    paths:
    - vendor/
  script:
    - pwd
    - su yawik -c "composer install"

phpunit:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - ./vendor/bin/phpunit

behat:
  stage: test
  allow_failure: true
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - su yawik -c "composer install"
    - mkdir -p build/behat
    - mkdir -p build/mails
    - cp .gitlab/autoload/*.* test/sandbox/config/autoload/
    - composer run serve --timeout=0 > /dev/null 2>&1 &
    - ./vendor/bin/behat --strict --no-interaction

deploy_master:
  stage: deploy
  environment:
    name: live/$CI_COMMIT_REF_NAME
    url: https://yawik.org/demo/
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - dep deploy
  resource_group: production